import postgres from 'postgres';
import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const dbUrl = process.env.SUPABASE_DB_URL;

if (!dbUrl) {
    console.error("❌ SUPABASE_DB_URL is missing in .env file");
    process.exit(1);
}

// Initialize the connection pool
const sql = postgres(dbUrl, { ssl: 'require' });

interface ProfileData {
    username: string;
    full_name: string;
    avatar_url?: string;
    curr_score?: number;
}

/**
 * Inserts a new profile into the database.
 * The ID is automatically generated by Postgres (gen_random_uuid).
 */
export async function createProfile(data: ProfileData) {
    const { 
        username, 
        full_name, 
        avatar_url = '', 
        curr_score = 0 
    } = data;

    try {
        const result = await sql`
            INSERT INTO public.profiles (
                username, 
                full_name, 
                avatar_url, 
                curr_score, 
                chat_history
            ) VALUES (
                ${username}, 
                ${full_name}, 
                ${avatar_url}, 
                ${curr_score}, 
                ${sql.json([])} -- Initializes empty chat history
            )
            RETURNING *
        `;

        console.log(`✅ Profile created!`);
        console.table({
            id: result[0].id,
            username: result[0].username,
            name: result[0].full_name
        });
        
        return result[0];
    } catch (error) {
        console.error("❌ Error adding profile:", error);
        throw error;
    }
}

/**
 * Execution block for running directly via terminal
 */
async function run() {
    console.log("🚀 Attempting to add a new profile...");
    
    try {
        await createProfile({
            username: 'supraja_dev',
            full_name: 'Supraja Srikanth',
            avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Supraja',
            curr_score: 0
        });
    } catch (err) {
        // Error already logged in createProfile
    } finally {
        await sql.end();
        console.log("🏁 Database connection closed.");
    }
}

// This checks if the file is being run directly
const isMain = process.argv[1]?.includes('profile_utils.ts') || process.argv[1]?.includes('tsx');

if (isMain) {
    run();
}